/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  skill: [
    'skill/introduction',
    {
      label: '代码规范',
      type: 'category',
      link: {
        type: 'doc',
        id: 'skill/code-specification/code-specification-guides',
      },
      items: ['skill/code-specification/eslint'],
    },
    {
      label: 'Vue',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: ['skill/vue/pinia'],
    },
    {
      label: 'React',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/react',
        },
      ],
    },

    {
      label: 'JavaScript',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/js',
        },
      ],
    },
    {
      label: 'Node',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/node',
        },
      ],
    },
    {
      label: 'Css',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/css',
        },
      ],
    },
    {
      label: 'Git',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/git',
        },
      ],
    },
    {
      label: '算法',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/algorithm',
        },
      ],
    },
    // {
    //   label: '逆向',
    //   type: 'category',
    //   link: {
    //     title: '逆向笔记',
    //     description: 'Web逆向与安卓逆向笔记',
    //     type: 'generated-index',
    //     keywords: ['reverse', 'web', 'android', 'frida'],
    //   },
    //   items: [
    //     {
    //       label: '安卓',
    //       type: 'category',
    //       link: {
    //         type: 'generated-index',
    //       },
    //       items: [
    //         {
    //           type: 'autogenerated',
    //           dirName: 'skill/reverse/android',
    //         },
    //       ],
    //     },
    // {
    //   label: 'Web',
    //   type: 'category',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'skill/reverse/web',
    //     },
    //   ],
    // },
    // {
    //       label: '密码学',
    //       type: 'category',
    //       items: [
    //         {
    //           type: 'autogenerated',
    //           dirName: 'skill/reverse/crypto',
    //         },
    //       ],
    //     },
    //   ],
    // },
    // {
    //   label: 'Docker',
    //   type: 'category',
    //   link: {
    //     type: 'generated-index',
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'skill/docker',
    //     },
    //   ],
    // },
    {
      label: '数据库',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['database', 'mysql', 'mongodb', 'redis', 'elasticsearch'],
      },
      items: [
        {
          label: 'Mysql',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/mysql/mysql-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/mysql',
            },
          ],
        },
        {
          label: 'MongoDB',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/mongo/mongodb-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/mongo',
            },
          ],
        },
        {
          label: 'Redis',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/redis/redis-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/redis',
            },
          ],
        },
        {
          label: 'Elasticsearch',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/database/elasticsearch/elasticsearch-note',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/database/elasticsearch',
            },
          ],
        },
      ],
    },
    // {
    //   label: '杂项',
    //   type: 'category',
    //   link: {
    //     type: 'generated-index',
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'skill/other',
    //     },
    //   ],
    // },
  ],
  tools: [
    'tools/introduction',
    'tools/wappalyzer-recognize-technology',
    'tools/vscode-config',
    'tools/vite-plugin',
  ],
}

module.exports = sidebars
